### ISSUE TITLE
Segna automaticamente la consumazione nel file di contabilità dei pranzi

### ISSUE THREAD

**Issue by feedingaliencat** [develersrl/lunches#12]
Una volta che abbiamo l'ordine su Tinabot, si potrebbe aggiornare direttamente il google docs di contabilità dei pranzi, senza dover segnare a mano dopo (pur lasciando aperte le modifiche manuali come ora).

**Comment by giannimassi** [comment]
Chiudo perchè è una feature che è stata implementata
