### ISSUE TITLE
Sostituire espressioni del tipo "Metodologia: contorno" con italiano più meglio

### ISSUE THREAD

**Issue by 7lb** [develersrl/lunches#14]
La lista di contorni del tuttobene disambigua i contorni usando uno schema del tipo "Metodologia: contorno", ad esempio "Vapore: carote" o "Grigliate: finocchi".

La cosa è utile al momento dell'ordinazione, meno al momento di inviare gli ordini al tuttobene.
Un ordine così composto è ad esempio "Salmone con pomodorini con Vapore: carote".

Considerando che in tutti i menu compaiono sempre cose al vapore e alla griglia, e senza stare ad applicare euristiche complicate, la mia proposta è la seguente:

1. replace letterale di `[Vv]apore: <foo>` in `foo al vapore`
2. replace letterale di `[Gg]riglia.*: <foo>` in `foo alla griglia`

E se in futuro arrivano altre metodologie possiamo metterle nella whitelist se e quando serve.

L'esempio di cui sopra in questo modo diventerebbe "Salmone con pomodorini con carote al vapore"

**Comment by batt** [comment]
fixed in 9afe8ceb6ed28a0e8eb163987eae54b60dc8cace
