### ISSUE TITLE
Possibilità di ordinare lo stesso piatto di un'altra persona

### ISSUE THREAD

**Issue by plorefice** [develersrl/lunches#15]
Se qualcuno ha già ordinato la combo di piatti che vorrei prendere anch'io, sarebbe ganzo poter scrivere `per me quello che ha preso [nick]`, così da non dover combattere con i vai `&`, `+` e compagnia bella.

Bonus points se posso addirittura abbreviare il nome!

**Comment by batt** [comment]
Implemented in #21
