### ISSUE TITLE
Gestione prezzi del menù

### ISSUE THREAD

**Issue by batt** [develersrl/lunches#27]
Per l'amministrazione di Develer, farebbe molto comodo che tinabot tenesse traccia del costo dei singoli piatti e facesse un report all'amministrazione, giorno per giorno.

Dovrebbe essere sufficiente aggiungere un campo con il costo parsato dal menù e poi bisognerebbe aggiungere un task che parsa l'ordine e invia una mail riepilogativa all'amministrazione.

**Comment by batt** [comment]
WIP in #28

**Comment by giannimassi** [comment]
https://github.com/develersrl/lunches/pull/29
