### ISSUE TITLE
Pinga utenti che non hanno ancora ordinato

### ISSUE THREAD

**Issue by savo92** [develersrl/lunches#5]
Succede constantemente che la gente si scordi di ordinare e quando colui che gestisce l'invio dell'ordine inizia a dumpare l'ordine da inviare, tutti i ricordano che devono ordinare e parte il macello su #chat_cibo. Questo si potrebbe forse prevenire se Tinabot9k ad una cert'ora iniziasse a controllare l'attuale ordine e avvisasse chi ancora non è presente in quella lista, magari mandandogli un DM se possibile.
Questa feature dovrebbe però essere disattivabile da uno specifico utente, nel caso che quest ultimo non ordinasse mai al TB

**Comment by batt** [comment]
Fixed in 2fe6d550875958a9e91849d9d2fa408b50f28ffa
